### ISSUE TITLE
Need reputations at max rep marked correctly

### ISSUE THREAD

**Issue by allygator** [allygator/wowReputationCalculator#1]
The API has reputations at "Best Friend" and "Exalted" at 0, which is also "Hated".

**Comment by SammyIsra** [comment]
Isn't this already solved? By this function?
https://github.com/allygator/wowReputationCalculator/blob/master/src/components/Reputations.js#L74

**Comment by allygator** [comment]
No that function is for the filter to hide completed reps, though this issue is solved by https://github.com/allygator/wowReputationCalculator/blob/3b2d0caba21d4b2c0a5aa35879bd3a60bb71f3bb/src/components/Reputations.js#L63

**Comment by allygator** [comment]
This is solved by https://github.com/allygator/wowReputationCalculator/blob/3b2d0caba21d4b2c0a5aa35879bd3a60bb71f3bb/src/components/Reputations.js#L84
